import { CommissionType, TranslationDictionary, WebsiteSettings } from "./types";

export const GOOGLE_MAPS_API_KEY = "AlzaSyBbpQRzzuNpV7_z7SvgaLbsIpLNi-OOdoQ";
export const WHATSAPP_NUMBER_DEFAULT = "967771603365";

export const DEFAULT_SETTINGS: WebsiteSettings = {
  appNameEn: "ALALAMI",
  appNameAr: "العالمي",
  logoUrl: "/logo.png",
  defaultLanguage: 'ar',
  contactPhone: "+967 771 603 365",
  contactEmail: "info@alalami.com",
  contactAddressEn: "Sana'a, Yemen",
  contactAddressAr: "صنعاء، اليمن",
  workingHoursEn: "Sat-Thu: 8am - 9pm",
  workingHoursAr: "السبت - الخميس: ٨ صباحاً - ٩ مساءً",
  facebookUrl: "",
  instagramUrl: "",
  whatsappNumber: WHATSAPP_NUMBER_DEFAULT,
  tiktokUrl: "",
  youtubeUrl: "",
  footerTextEn: "The #1 Auto Spare Parts Marketplace in Yemen.",
  footerTextAr: "السوق الأول لقطع غيار السيارات في اليمن.",
  defaultCommissionType: CommissionType.PERCENT,
  defaultCommissionValue: 5,
  lowStockThreshold: 5,
};

export const TRANSLATIONS: TranslationDictionary = {
  // General
  appName: { en: "ALALAMI", ar: "العالمي" },
  home: { en: "Home", ar: "الرئيسية" },
  search: { en: "Search", ar: "بحث" },
  login: { en: "Sign In", ar: "تسجيل الدخول" },
  logout: { en: "Logout", ar: "تسجيل الخروج" },
  register: { en: "Create Account", ar: "إنشاء حساب" },
  dashboard: { en: "Dashboard", ar: "لوحة التحكم" },
  profile: { en: "My Profile", ar: "ملفي الشخصي" },
  welcome: { en: "Find the best auto parts in Yemen", ar: "اعثر على أفضل قطع غيار السيارات في اليمن" },
  welcomeSub: { en: "Search by part name, number, vehicle, or shop. Compare prices and buy with confidence.", ar: "ابحث باسم القطعة أو رقمها أو السيارة أو المحل. قارن الأسعار واشترِ بثقة." },
  searchPlaceholder: { en: "Search parts, numbers, vehicles, shops...", ar: "ابحث عن قطع أو أرقام أو سيارات أو محلات..." },
  viewDetails: { en: "View Details", ar: "التفاصيل" },
  price: { en: "Price", ar: "السعر" },
  condition: { en: "Condition", ar: "الحالة" },
  new: { en: "New", ar: "جديد" },
  used: { en: "Used", ar: "مستعمل" },
  addToCart: { en: "Add to Cart", ar: "أضف إلى السلة" },
  contactSeller: { en: "Contact Seller", ar: "تواصل مع المحل" },
  shopName: { en: "Shop", ar: "المتجر" },
  branch: { en: "Branch", ar: "الفرع" },
  location: { en: "Location", ar: "الموقع" },
  availability: { en: "Availability", ar: "التوفر" },
  inStock: { en: "In Stock", ar: "متوفر" },
  contactPrice: { en: "Contact for price", ar: "السعر عند التواصل" },
  trustGuaranteed: { en: "Trusted sellers", ar: "بائعون موثوقون" },
  trustGuaranteedDesc: { en: "Approved & verified shops", ar: "محلات معتمدة وموثقة" },
  deliveryAvailable: { en: "Delivery", ar: "التوصيل" },
  deliveryAvailableDesc: { en: "Pickup or courier", ar: "استلام أو توصيل" },
  verifiedShopsDesc: { en: "Real parts, real reviews", ar: "قطع أصلية وتقييمات حقيقية" },
  support247: { en: "Support 24/7", ar: "دعم على مدار الساعة" },
  support247Desc: { en: "We're always here", ar: "نحن دائماً في خدمتك" },
  featuredParts: { en: "Featured parts", ar: "قطع مميزة" },
  topShops: { en: "Top rated shops", ar: "أفضل المحلات" },
  requestPartCta: { en: "Can't find the part you need?", ar: "لم تجد القطعة التي تبحث عنها؟" },
  requestPartCtaDesc: { en: "Submit a request and our network of shops will source it for you at the best price.", ar: "أرسل طلبك وسيبحث لك تشبكة محلاتنا عن القطعة بأفضل سعر." },
  outOfStock: { en: "Out of Stock", ar: "غير متوفر" },
  adminPanel: { en: "Admin Panel", ar: "لوحة الإدارة" },
  sellerZone: { en: "Seller Zone", ar: "منطقة البائعين" },
  myParts: { en: "My Products", ar: "منتجاتي" },
  addPart: { en: "Add Product", ar: "إضافة منتج" },
  sales: { en: "Sales", ar: "المبيعات" },
  users: { en: "Users", ar: "المستخدمون" },
  shops: { en: "Shops", ar: "المحلات" },
  totalRevenue: { en: "Total Revenue", ar: "إجمالي الإيرادات" },
  active: { en: "Active", ar: "نشط" },
  inactive: { en: "Inactive", ar: "غير نشط" },
  suspended: { en: "Suspended", ar: "موقوف" },
  deactivated: { en: "Deactivated", ar: "معطل" },
  compare: { en: "Compare", ar: "مقارنة" },
  contactViaWhatsapp: { en: "Contact via WhatsApp", ar: "تواصل عبر واتساب" },
  callShop: { en: "Call Shop", ar: "اتصل بالمتجر" },
  description: { en: "Description", ar: "الوصف" },
  workingHours: { en: "Working Hours", ar: "ساعات العمل" },
  brands: { en: "Brands", ar: "الماركات" },
  categories: { en: "Categories", ar: "الفئات" },
  inventory: { en: "Inventory", ar: "المخزون" },
  reports: { en: "Reports", ar: "التقارير" },
  costPrice: { en: "Cost Price", ar: "سعر التكلفة" },
  profit: { en: "Profit", ar: "الربح" },
  resetPassword: { en: "Reset Password", ar: "إعادة تعيين كلمة المرور" },
  status: { en: "Status", ar: "الحالة" },
  carBrand: { en: "Car Brand", ar: "ماركة السيارة" },
  category: { en: "Category", ar: "الفئة" },
  websiteSettings: { en: "Website Settings", ar: "إعدادات الموقع" },
  saveChanges: { en: "Save Changes", ar: "حفظ التغييرات" },
  cancel: { en: "Cancel", ar: "إلغاء" },
  edit: { en: "Edit", ar: "تعديل" },
  delete: { en: "Delete", ar: "حذف" },
  deleteConfirm: { en: "Are you sure? This action cannot be undone.", ar: "هل أنت متأكد؟ لا يمكن التراجع عن هذا الإجراء." },
  whatsapp: { en: "WhatsApp", ar: "واتساب" },
  email: { en: "Email", ar: "البريد الإلكتروني" },
  logoUrl: { en: "Logo URL", ar: "رابط الشعار" },
  welcomeBack: { en: "Welcome back to ALALAMI", ar: "مرحباً بعودتك إلى العالمي" },
  empty: { en: "Nothing here yet", ar: "لا يوجد شيء هنا بعد" },
  emptyAction: { en: "Start exploring", ar: "ابدأ الاستكشاف" },
  all: { en: "All", ar: "الكل" },
  save: { en: "Save", ar: "حفظ" },
  loading: { en: "Loading...", ar: "جارٍ التحميل..." },
  errorOccurred: { en: "Something went wrong", ar: "حدث خطأ ما" },
  retry: { en: "Retry", ar: "إعادة المحاولة" },
  results: { en: "results", ar: "نتيجة" },
  noResults: { en: "No results found", ar: "لا توجد نتائج" },
  noResultsHint: { en: "Try a different keyword or reset the filters.", ar: "جرّب كلمة مختلفة أو أعد تعيين الفلاتر." },
  filters: { en: "Filters", ar: "الفلاتر" },
  clearAll: { en: "Clear all", ar: "مسح الكل" },
  inStockOnly: { en: "In stock only", ar: "المتوفر فقط" },
  maxPrice: { en: "Max price", ar: "الحد الأقصى للسعر" },
  filterByVehicle: { en: "Filter by your vehicle", ar: "تصفية حسب سيارتك" },
  selectMake: { en: "Select make", ar: "اختر الماركة" },
  selectModel: { en: "Select model", ar: "اختر الموديل" },
  selectGeneration: { en: "Select generation", ar: "اختر الجيل" },
  selectEngine: { en: "Select engine", ar: "اختر المحرك" },
  loadMore: { en: "Load more", ar: "المزيد" },
  clearFilters: { en: "Clear filters", ar: "مسح الفلاتر" },
  apply: { en: "Apply", ar: "تطبيق" },
  currency: { en: "Currency", ar: "العملة" },
  quantity: { en: "Qty", ar: "الكمية" },
  country: { en: "Country", ar: "الدولة" },
  city: { en: "City", ar: "المدينة" },
  manufacturer: { en: "Manufacturer", ar: "الشركة المصنعة" },
  partNumber: { en: "Part Number", ar: "رقم القطعة" },
  oemNumber: { en: "OEM Number", ar: "رقم OEM" },
  vehicle: { en: "Vehicle", ar: "المركبة" },
  relatedToVehicle: { en: "Filters for your vehicle", ar: "تصفية حسب سيارتك" },

  // Registration
  fullName: { en: "Full Name", ar: "الاسم الكامل" },
  username: { en: "Username", ar: "اسم المستخدم" },
  password: { en: "Password", ar: "كلمة المرور" },
  confirmPassword: { en: "Confirm Password", ar: "تأكيد كلمة المرور" },
  phone: { en: "Phone Number", ar: "رقم الهاتف" },
  address: { en: "Address", ar: "العنوان" },
  registerSuccess: { en: "Registration successful!", ar: "تم التسجيل بنجاح!" },
  passwordsDoNotMatch: { en: "Passwords do not match", ar: "كلمات المرور غير متطابقة" },
  usernameTaken: { en: "Username is already taken", ar: "اسم المستخدم مأخوذ مسبقاً" },
  ownedCars: { en: "Car Brands You Own", ar: "ماركات السيارات التي تملكها" },
  preferredCats: { en: "Preferred Categories", ar: "الفئات المفضلة" },
  createAccountAs: { en: "Create your account", ar: "أنشئ حسابك" },
  alreadyHaveAccount: { en: "Already have an account?", ar: "لديك حساب بالفعل؟" },
  dontHaveAccount: { en: "Don't have an account?", ar: "ليس لديك حساب؟" },
  signInOther: { en: "Or continue with", ar: "أو تابع باستخدام" },
  phoneOtp: { en: "Phone + OTP", ar: "هاتف + رمز تحقق" },
  emailPassword: { en: "Email / Password", ar: "بريد / كلمة مرور" },
  otpCode: { en: "Verification Code", ar: "رمز التحقق" },
  sendOtp: { en: "Send Code", ar: "إرسال الرمز" },
  verify: { en: "Verify & Sign in", ar: "تحقق ودخول" },
  otpHint: { en: "Demo: any 6-digit code works (e.g. 123456)", ar: "تجريبي: أي رمز من 6 أرقام يعمل (مثال: 123456)" },
  forgotPassword: { en: "Forgot password?", ar: "نسيت كلمة المرور؟" },
  signInWithGoogle: { en: "Continue with Google", ar: "المتابعة عبر جوجل" },
  signInWithApple: { en: "Continue with Apple", ar: "المتابعة عبر آبل" },
  googleHint: { en: "Demo: signs into a sample customer account", ar: "تجريبي: تسجيل الدخول إلى حساب عميل تجريبي" },
  appleHint: { en: "Demo: signs into a sample customer account", ar: "تجريبي: تسجيل الدخول إلى حساب عميل تجريبي" },
  wrongOtp: { en: "Invalid or expired verification code", ar: "رمز التحقق غير صحيح أو منتهي" },

  // Auth / roles
  roleCustomer: { en: "Customer", ar: "عميل" },
  roleShopOwner: { en: "Shop Owner", ar: "صاحب متجر" },
  roleShopEmployee: { en: "Shop Employee", ar: "موظف متجر" },
  roleAdmin: { en: "Admin", ar: "مسؤول" },
  roleSuperAdmin: { en: "Super Admin", ar: "مدير عام" },
  unauthorized: { en: "You do not have permission to access this page", ar: "ليس لديك صلاحية للوصول إلى هذه الصفحة" },
  forbiddenTitle: { en: "403 — Access denied", ar: "403 — تم رفض الوصول" },
  notFoundTitle: { en: "404 — Page not found", ar: "404 — الصفحة غير موجودة" },
  goHome: { en: "Back to home", ar: "العودة للرئيسية" },

  // Extras used by preserved pages
  adminAddShop: { en: "Add Shop Owner", ar: "إضافة مالك متجر" },
  ownerName: { en: "Shop Owner Name", ar: "اسم مالك المتجر" },
  shopNameField: { en: "Shop Name", ar: "اسم المتجر" },
  latitude: { en: "Latitude", ar: "خط العرض" },
  longitude: { en: "Longitude", ar: "خط الطول" },
  notes: { en: "Notes / Specialization", ar: "ملاحظات / التخصص" },
  headerSettings: { en: "Header Settings", ar: "إعدادات الهيدر" },
  footerSettings: { en: "Footer Settings", ar: "إعدادات الفوتر" },
  socialSettings: { en: "Social Media Settings", ar: "إعدادات التواصل الاجتماعي" },
  contactSettings: { en: "Contact Info Settings", ar: "إعدادات معلومات الاتصال" },
  openMaps: { en: "Open Maps", ar: "افتح الخريطة" },
  allUsers: { en: "All Users", ar: "كل المستخدمين" },
  onlySellers: { en: "Sellers", ar: "البائعين" },
  onlyCustomers: { en: "Customers", ar: "العملاء" },
  onlyAdmins: { en: "Admins", ar: "المسؤولين" },
  stockMovement: { en: "Stock Movement Log", ar: "سجل حركة المخزون" },
  lowStock: { en: "Low Stock Alert", ar: "تنبيه انخفاض المخزون" },
  currentStock: { en: "Current Stock", ar: "المخزون الحالي" },
  changeType: { en: "Change Type", ar: "نوع التغيير" },
  date: { en: "Date", ar: "التاريخ" },
  reason: { en: "Reason", ar: "السبب" },
  uploadImage: { en: "Upload Images", ar: "رفع صور" },
  browse: { en: "Browse", ar: "تصفح" },
  maxSize: { en: "Max 2MB per image", ar: "أقصى حجم 2 ميجابايت" },
  remove: { en: "Remove", ar: "إزالة" },
  manageCategories: { en: "Manage Categories", ar: "إدارة الفئات" },
  addCategory: { en: "Add Category", ar: "إضافة فئة" },
  categoryNameEn: { en: "Category Name (EN)", ar: "اسم الفئة (إنجليزي)" },
  categoryNameAr: { en: "Category Name (AR)", ar: "اسم الفئة (عربي)" },
  activeCategories: { en: "Active Categories", ar: "الفئات النشطة" },
  externalRequest: { en: "External Sales Request", ar: "طلب مبيعات خارجي" },
  requestPart: { en: "Request a Part", ar: "اطلب قطعة" },
  contactUs: { en: "Contact Us", ar: "تواصل بنا" },
  inbox: { en: "Inbox", ar: "صندوق الوارد" },
  sendMessage: { en: "Send Message", ar: "إرسال الرسالة" },
  requestSubmitted: { en: "Your request has been submitted. You will be contacted soon.", ar: "تم تقديم طلبك بنجاح. سيتم التواصل معك قريباً." },
  carModel: { en: "Car Model", ar: "موديل السيارة" },
  modelYear: { en: "Model Year", ar: "سنة الموديل" },
  partDesc: { en: "Part Description", ar: "وصف القطعة" },
  messageBody: { en: "Message", ar: "الرسالة" },
  submit: { en: "Submit", ar: "إرسال" },
  markRead: { en: "Mark as Read", ar: "تمييز كمقروء" },
  reply: { en: "Reply", ar: "رد" },
  from: { en: "From", ar: "من" },
  unreadMessages: { en: "Unread Messages", ar: "رسائل غير مقروءة" },

  // New: products
  product: { en: "Product", ar: "المنتج" },
  priceHidden: { en: "Contact the shop", ar: "تواصل مع المحل" },
  priceVisibility: { en: "Price visibility", ar: "إظهار السعر" },
  showPrice: { en: "Show price", ar: "إظهار السعر" },
  hidePrice: { en: "Hide price (Contact shop)", ar: "إخفاء السعر (تواصل مع المحل)" },
  saleMode: { en: "Purchase mode", ar: "طريقة الشراء" },
  onlineOnly: { en: "Online purchase", ar: "شراء إلكتروني" },
  externalOnly: { en: "External purchase (contact shop)", ar: "شراء خارجي (تواصل مع المحل)" },
  onlineAndExternal: { en: "Both online & external", ar: "إلكتروني وخارجي" },
  barcode: { en: "Barcode", ar: "الباركود" },
  qrCode: { en: "QR Code", ar: "رمز QR" },
  compatibleVehicles: { en: "Compatible vehicles", ar: "السيارات المتوافقة" },
  addFitment: { en: "Add compatible vehicle", ar: "إضافة سيارة متوافقة" },
  stock: { en: "Stock", ar: "المخزون" },
  minStock: { en: "Low stock threshold", ar: "حد التنبيه للمخزون" },
  activeProduct: { en: "Active product", ar: "منتج نشط" },
  newArrivals: { en: "New Arrivals", ar: "وصل حديثاً" },
  shopOffers: { en: "Offers from other shops", ar: "عروض محلات أخرى" },
  compareOffers: { en: "Compare offers", ar: "قارن العروض" },
  selected: { en: "Selected", ar: "محدد" },
  originalPrice: { en: "Original price", ar: "السعر الأصلي" },

  // Cart
  cart: { en: "Cart", ar: "السلة" },
  cartGroupByShop: { en: "Items are grouped by shop", ar: "المُنتجات مجمّعة حسب المحل" },
  cartEmpty: { en: "Your cart is empty", ar: "سلتك فارغة" },
  cartEmptyDesc: { en: "Browse parts and add them to your cart to get started.", ar: "تصفح القطع وأضفها إلى سلتك للبدء." },
  browseParts: { en: "Browse parts", ar: "تصفح القطع" },
  clearCart: { en: "Clear cart", ar: "إفراغ السلة" },
  orderSummary: { en: "Order summary", ar: "ملخص الطلب" },
  cartNote: { en: "Total price may change based on delivery and shop offers.", ar: "قد يتغير السعر الإجمالي حسب التوصيل وعروض المحلات." },
  cartEmptyHint: { en: "Add some parts before checking out.", ar: "أضف بعض القطع قبل إتمام الطلب." },
  subtotal: { en: "Subtotal", ar: "المجموع الفرعي" },
  deliveryFee: { en: "Delivery fee", ar: "رسوم التوصيل" },
  total: { en: "Total", ar: "الإجمالي" },
  checkout: { en: "Checkout", ar: "إتمام الطلب" },
  continueShopping: { en: "Continue shopping", ar: "مواصلة التسوق" },
  removeItem: { en: "Remove", ar: "حذف" },

  // Checkout & orders
  checkoutTitle: { en: "Checkout", ar: "إتمام الطلب" },
  deliveryType: { en: "Delivery method", ar: "طريقة التوصيل" },
  pickup: { en: "Pickup from shop", ar: "استلام من المحل" },
  shopDelivery: { en: "Shop delivery", ar: "توصيل من المحل" },
  deliveryCompany: { en: "Delivery company", ar: "شركة توصيل" },
  paymentMethod: { en: "Payment method", ar: "طريقة الدفع" },
  cashOnDelivery: { en: "Cash on delivery", ar: "الدفع عند الاستلام" },
  bankTransfer: { en: "Bank transfer", ar: "تحويل بنكي" },
  eWallet: { en: "E-wallet", ar: "محفظة إلكترونية" },
  bankCard: { en: "Bank card", ar: "بطاقة بنكية" },
  externalNote: { en: "This order includes external-purchase items. Complete it via the shop directly.", ar: "يحتوي هذا الطلب على منتجات شراء خارجي. أكمله مباشرة مع المحل." },
  placeOrder: { en: "Place order", ar: "تأكيد الطلب" },
  deliveryMethod: { en: "Delivery method", ar: "طريقة التوصيل" },
  deliveryAddress: { en: "Delivery address", ar: "عنوان التوصيل" },
  selectAddress: { en: "Please select an address", ar: "الرجاء اختيار عنوان" },
  noAddresses: { en: "No saved addresses yet.", ar: "لا توجد عناوين محفوظة بعد." },
  addressLabel: { en: "Label (Home, Work…)", ar: "التسمية (منزل، عمل…)" },
  streetAddress: { en: "Street address", ar: "العنوان التفصيلي" },
  addressSaved: { en: "Address saved", ar: "تم حفظ العنوان" },
  paymentNote: { en: "You will confirm payment details on the next screen.", ar: "ستؤكد تفاصيل الدفع في الشاشة التالية." },
  orderNotes: { en: "Order notes", ar: "ملاحظات الطلب" },
  walletBalance: { en: "Wallet", ar: "المحفظة" },
  more: { en: "more", ar: "مزيد" },
  backToCart: { en: "Back to cart", ar: "العودة إلى السلة" },
  orderPlaced: { en: "Order placed successfully!", ar: "تم إنشاء الطلب بنجاح!" },
  orders: { en: "Orders", ar: "الطلبات" },
  order: { en: "Order", ar: "الطلب" },
  orderNumber: { en: "Order number", ar: "رقم الطلب" },
  orderItems: { en: "Items", ar: "المنتجات" },
  trackOrder: { en: "Track order", ar: "تتبع الطلب" },
  noOrders: { en: "No orders yet", ar: "لا توجد طلبات بعد" },
  pending: { en: "Pending", ar: "قيد الانتظار" },
  confirmed: { en: "Confirmed", ar: "مؤكد" },
  preparing: { en: "Preparing", ar: "قيد التحضير" },
  ready: { en: "Ready", ar: "جاهز" },
  completed: { en: "Completed", ar: "مكتمل" },
  rejected: { en: "Rejected", ar: "مرفوض" },
  cancelled: { en: "Cancelled", ar: "ملغي" },
  confirmOrder: { en: "Confirm order", ar: "تأكيد الطلب" },
  rejectOrder: { en: "Reject order", ar: "رفض الطلب" },
  cancelOrder: { en: "Cancel order", ar: "إلغاء الطلب" },
  myOrders: { en: "My orders", ar: "طلباتي" },
  orderCancelled: { en: "Order cancelled", ar: "تم إلغاء الطلب" },
  orderRejected: { en: "This order was rejected. Contact the shop for details.", ar: "تم رفض هذا الطلب. تواصل مع المحل للتفاصيل." },
  qty: { en: "Qty", ar: "الكمية" },
  delivery: { en: "Delivery", ar: "التوصيل" },
  paid: { en: "Paid", ar: "مدفوع" },
  refunded: { en: "Refunded", ar: "مسترجع" },
  pendingPayment: { en: "Pending payment", ar: "في انتظار الدفع" },
  allOrders: { en: "All orders", ar: "كل الطلبات" },
  commission: { en: "Commission", ar: "العمولة" },
  startPreparing: { en: "Start preparing", ar: "بدء التحضير" },
  markReady: { en: "Mark as ready", ar: "تحديد كجاهز" },
  markCompleted: { en: "Complete order", ar: "إتمام الطلب" },
  orderTimeline: { en: "Order status", ar: "حالة الطلب" },
  orderedAt: { en: "Ordered at", ar: "تاريخ الطلب" },

  // Vehicles & garage
  vehicles: { en: "Vehicles", ar: "السيارات" },
  myGarage: { en: "My Garage", ar: "جراجي" },
  addVehicle: { en: "Add vehicle", ar: "إضافة سيارة" },
  fillVehicle: { en: "Please select make and model", ar: "الرجاء اختيار الماركة والموديل" },
  vehicleAdded: { en: "Vehicle added to garage", ar: "تمت إضافة السيارة إلى المرآب" },
  complaintSent: { en: "Complaint submitted", ar: "تم إرسال الشكوى" },
  fillAll: { en: "Please fill all required fields", ar: "الرجاء تعبئة جميع الحقول المطلوبة" },
  noComplaints: { en: "No complaints yet", ar: "لا توجد شكاوى بعد" },
  make: { en: "Make", ar: "ماركة" },
  model: { en: "Model", ar: "موديل" },
  generation: { en: "Generation", ar: "جيل" },
  engine: { en: "Engine", ar: "المحرك" },
  filterByMyVehicle: { en: "Show only parts for my vehicle", ar: "عرض القطع المتوافقة مع سيارتي فقط" },
  noGarage: { en: "No vehicles saved yet", ar: "لا توجد سيارات محفوظة بعد" },
  addFirstVehicle: { en: "Add your first vehicle to search compatible parts.", ar: "أضف سيارتك الأولى للبحث عن القطع المتوافقة." },
  selectVehicle: { en: "Select vehicle", ar: "اختر السيارة" },
  allVehicles: { en: "All vehicles", ar: "كل السيارات" },
  compatibleWithMyVehicle: { en: "Compatible with my vehicle", ar: "متوافقة مع سيارتي" },
  vehicleNotSupported: { en: "No filters matched for this vehicle.", ar: "لا فلاتر مطابقة لهذه السيارة." },

  // Shops
  shopApproval: { en: "Shop registration", ar: "تسجيل المتجر" },
  registerShop: { en: "Register your shop", ar: "سجّل متجرك" },
  shopStatusPending: { en: "Pending review", ar: "قيد المراجعة" },
  shopStatusApproved: { en: "Approved", ar: "معتمد" },
  shopStatusRejected: { en: "Rejected", ar: "مرفوض" },
  shopStatusDisabled: { en: "Disabled", ar: "معطل" },
  shopPendingMessage: { en: "Your shop is pending admin review. You cannot sell yet.", ar: "متجرك قيد المراجعة. لا يمكنك البيع بعد." },
  shopDisabledMessage: { en: "Your shop has been disabled by the platform.", ar: "تم تعطيل متجرك من قبل المنصة." },
  shopRejectedMessage: { en: "Your shop registration was rejected.", ar: "تم رفض تسجيل متجرك." },
  shopDetails: { en: "Shop details", ar: "بيانات المتجر" },
  branches: { en: "Branches", ar: "الفروع" },
  addBranch: { en: "Add branch", ar: "إضافة فرع" },
  employees: { en: "Employees", ar: "الموظفون" },
  addEmployee: { en: "Add employee", ar: "إضافة موظف" },
  assignPermissions: { en: "Assign permissions", ar: "تحديد الصلاحيات" },
  shopRating: { en: "Shop rating", ar: "تقييم المتجر" },
  writeReview: { en: "Write a review", ar: "اكتب تقييماً" },
  buyNow: { en: "Buy now", ar: "اشترِ الآن" },
  verified: { en: "Verified", ar: "موثوق" },
  onlineOrder: { en: "Online order", ar: "طلب إلكتروني" },
  relatedParts: { en: "Related parts", ar: "قطع مشابهة" },
  samePartOffers: { en: "Offers for the same part", ar: "عروض لنفس القطعة" },
  genuineGuarantee: { en: "Genuine guarantee", ar: "ضمان أصالة" },
  returns: { en: "Easy returns", ar: "إرجاع سهل" },
  deliveryMethods: { en: "Multiple delivery options", ar: "خيارات توصيل متعددة" },
  contactShop: { en: "Contact shop", ar: "تواصل مع المحل" },
  addedToCart: { en: "Added to cart", ar: "أُضيفت إلى السلة" },
  wishlistAdded: { en: "Added to wishlist", ar: "أُضيفت إلى المفضلة" },
  reviews: { en: "Reviews", ar: "التقييمات" },
  noReviews: { en: "No reviews yet. Be the first!", ar: "لا توجد تقييمات بعد. كن أول من يقيّم!" },
  yourRating: { en: "Your rating", ar: "تقييمك" },
  yourComment: { en: "Your comment", ar: "تعليقك" },
  submitReview: { en: "Submit review", ar: "إرسال التقييم" },
  reviewSubmitted: { en: "Review submitted for moderation.", ar: "تم إرسال التقييم للمراجعة." },
  visitShop: { en: "Visit shop", ar: "زيارة المتجر" },
  registerShopTitle: { en: "Open a shop on ALALAMI", ar: "افتح متجرك على العالمي" },
  shopAdminReviewNote: { en: "Applications are reviewed by admins before approval.", ar: "تتم مراجعة الطلبات من قبل المسؤولين قبل الاعتماد." },

  // Shop management
  products: { en: "Products", ar: "المنتجات" },
  addProduct: { en: "Add product", ar: "إضافة منتج" },
  editProduct: { en: "Edit product", ar: "تعديل المنتج" },
  selectShop: { en: "Select shop", ar: "اختر المتجر" },
  selectBranch: { en: "Select branch", ar: "اختر الفرع" },
  importExcel: { en: "Import Excel/CSV", ar: "استيراد Excel/CSV" },
  importInventory: { en: "Import stock", ar: "استيراد المخزون" },
  downloadTemplate: { en: "Download template (CSV)", ar: "تنزيل نموذج (CSV)" },
  importSuccess: { en: "Import completed successfully", ar: "تم الاستيراد بنجاح" },
  importInstructions: { en: "CSV columns: nameEn, nameAr, partNumber, oemNumber, category, condition, price, currency, quantity, barcode", ar: "أعمدة CSV: nameEn, nameAr, partNumber, oemNumber, category, condition, price, currency, quantity, barcode" },
  stockAdjustment: { en: "Stock adjustment", ar: "تعديل المخزون" },
  transferStock: { en: "Transfer stock to branch", ar: "تحويل مخزون إلى فرع" },
  movementHistory: { en: "Movement history", ar: "سجل الحركات" },
  movementsIn: { en: "In", ar: "وارد" },
  movementsOut: { en: "Out", ar: "صادر" },
  movementsAdjustment: { en: "Adjustment", ar: "تسوية" },
  movementsReturn: { en: "Return", ar: "إرجاع" },
  movementsTransfer: { en: "Transfer", ar: "تحويل" },
  shopSettings: { en: "Shop settings", ar: "إعدادات المتجر" },
  commissionInfo: { en: "Platform commission", ar: "عمولة المنصة" },
  commissionPercent: { en: "Percentage", ar: "نسبة مئوية" },
  commissionFixed: { en: "Fixed amount", ar: "مبلغ ثابت" },
  commissionValue: { en: "Value", ar: "القيمة" },

  // Admin
  overview: { en: "Overview", ar: "نظرة عامة" },
  pendingShops: { en: "Pending approval", ar: "بانتظار المراجعة" },
  approve: { en: "Approve", ar: "اعتماد" },
  reject: { en: "Reject", ar: "رفض" },
  disable: { en: "Disable", ar: "تعطيل" },
  enableShop: { en: "Enable", ar: "تفعيل" },
  commissions: { en: "Commissions", ar: "العمولات" },
  payments: { en: "Payments", ar: "المدفوعات" },
  complaints: { en: "Complaints", ar: "الشكاوى" },
  notifications: { en: "Notifications", ar: "الإشعارات" },
  searchParts: { en: "Search parts by name, part number, or vehicle…", ar: "ابحث عن قطعة بالاسم أو رقم القطعة أو السيارة…" },
  viewAll: { en: "View all", ar: "عرض الكل" },
  noNotifications: { en: "No notifications yet", ar: "لا توجد إشعارات بعد" },
  shopOwner: { en: "Shop Owner", ar: "مالك المتجر" },
  shopEmployee: { en: "Shop Employee", ar: "موظف المتجر" },
  movements: { en: "Stock movements", ar: "حركات المخزون" },
  adminOverview: { en: "Overview", ar: "نظرة عامة" },
  manufacturers: { en: "Manufacturers", ar: "المصنعون" },
  banners: { en: "Banners", ar: "البنرات" },
  addBanner: { en: "Add banner", ar: "إضافة بنر" },
  auditLog: { en: "Audit log", ar: "سجل التدقيق" },
  searchLogs: { en: "Popular searches", ar: "أشهر عمليات البحث" },
  customers: { en: "Customers", ar: "العملاء" },
  moderation: { en: "Moderation", ar: "الإشراف" },
  statistics: { en: "Statistics", ar: "الإحصائيات" },
  ordersCount: { en: "Orders", ar: "الطلبات" },
  revenue: { en: "Revenue", ar: "الإيرادات" },
  activeUsers: { en: "Active users", ar: "المستخدمون النشطون" },
  approvedShops: { en: "Approved shops", ar: "المحلات المعتمدة" },
  productsCount: { en: "Products", ar: "المنتجات" },
  totalSales: { en: "Total sales", ar: "إجمالي المبيعات" },
  totalCommissions: { en: "Total commissions", ar: "إجمالي العمولات" },
  popularVehicles: { en: "Popular vehicles", ar: "أشهر السيارات" },
  shopPerformance: { en: "Shop performance", ar: "أداء المحلات" },
  monthlySales: { en: "Monthly sales", ar: "المبيعات الشهرية" },
  approveRejectNote: { en: "Approval note", ar: "ملاحظة المراجعة" },
  backToProfile: { en: "Back to profile", ar: "العودة إلى الملف الشخصي" },
  backToShops: { en: "Back to shops", ar: "العودة إلى المحلات" },
  clear: { en: "Clear", ar: "مسح" },
  mostReviewed: { en: "Most reviewed", ar: "الأكثر تقييماً" },
  name: { en: "Name", ar: "الاسم" },
  noProducts: { en: "No products yet", ar: "لا توجد منتجات بعد" },
  noResultsDesc: { en: "Try adjusting your search or filters", ar: "جرّب تعديل البحث أو عوامل التصفية" },
  searchShops: { en: "Search shops…", ar: "ابحث عن المحلات…" },
  shopNotFound: { en: "Shop not found", ar: "المحل غير موجود" },
  topRated: { en: "Top rated", ar: "الأعلى تقييماً" },

  // Notifications
  notificationsTitle: { en: "Notifications", ar: "الإشعارات" },
  markAllRead: { en: "Mark all as read", ar: "تحديد الكل كمقروء" },
  notificationOrderTitle: { en: "Order update", ar: "تحديث الطلب" },
  sendNotification: { en: "Send notification", ar: "إرسال إشعار" },
  targetUsers: { en: "Target", ar: "الفئة المستهدفة" },
  allCustomers: { en: "All customers", ar: "كل العملاء" },
  allShops: { en: "All shop owners", ar: "كل أصحاب المحلات" },

  // Wishlist
  wishlist: { en: "Wishlist", ar: "المفضلة" },
  addToWishlist: { en: "Add to Wishlist", ar: "أضف للمفضلة" },
  wishlistEmpty: { en: "Your wishlist is empty", ar: "قائمتك المفضلة فارغة" },

  // Profile
  myProfile: { en: "My profile", ar: "ملفي الشخصي" },
  memberSince: { en: "Member since", ar: "عضو منذ" },
  myAddresses: { en: "My addresses", ar: "عناويني" },
  addAddress: { en: "Add address", ar: "إضافة عنوان" },

  // Misc new
  languagePicker: { en: "Language", ar: "اللغة" },
  theme: { en: "Theme", ar: "المظهر" },
  searchByPartTitle: { en: "Search across our network", ar: "ابحث في شبكتنا" },
  trustBadges: { en: "Trust & safety", ar: "الثقة والأمان" },
  verifiedShops: { en: "Verified quality", ar: "جودة مضمونة" },
  genuineParts: { en: "Genuine & tested parts", ar: "قطع أصلية ومختبرة" },
  secureOrdering: { en: "Secure ordering", ar: "طلب آمن" },
  deliveryNetworks: { en: "Wide delivery network", ar: "شبكة توصيل واسعة" },
  shopRegistration: { en: "Sell with us", ar: "بِع معنا" },
  tooltipContactPrice: { en: "Price hidden by the shop. Contact them to ask.", ar: "السعر مخفي من قبل المحل. تواصل معه لمعرفته." },
} as const;