
import { TranslationDictionary, WebsiteSettings } from "./types";

export const GOOGLE_MAPS_API_KEY = "AlzaSyBbpQRzzuNpV7_z7SvgaLbsIpLNi-OOdoQ";
export const WHATSAPP_NUMBER_DEFAULT = "967771603365";

export const DEFAULT_SETTINGS: WebsiteSettings = {
  appNameEn: "ALALAMI",
  appNameAr: "العالمي",
  logoUrl: "",
  defaultLanguage: 'ar',
  contactPhone: "+967 771 603 365",
  contactEmail: "info@alalami.com",
  contactAddressEn: "Sana'a, Yemen",
  contactAddressAr: "صنعاء، اليمن",
  workingHoursEn: "Sat-Thu: 8am - 9pm",
  workingHoursAr: "السبت - الخميس: ٨ صباحاً - ٩ مساءً",
  facebookUrl: "",
  instagramUrl: "",
  whatsappNumber: WHATSAPP_NUMBER_DEFAULT,
  tiktokUrl: "",
  youtubeUrl: "",
  footerTextEn: "The #1 Auto Spare Parts Marketplace in Yemen.",
  footerTextAr: "السوق الأول لقطع غيار السيارات في اليمن."
};

export const TRANSLATIONS: TranslationDictionary = {
  // General
  appName: { en: "ALALAMI", ar: "العالمي" },
  home: { en: "Home", ar: "الرئيسية" },
  search: { en: "Search", ar: "بحث" },
  login: { en: "Login", ar: "تـسجيل الدخـول" },
  register: { en: "Create Account", ar: "إنشاء حساب" },
  dashboard: { en: "Dashboard", ar: "لوحة التحكم" },
  profile: { en: "My Profile", ar: "ملفي الشخصي" },
  logout: { en: "Logout", ar: "تسجيل خروج" },
  welcome: { en: "Find the best auto parts in Yemen", ar: "اعثر على أفضل قطع غيار السيارات في اليمن" },
  searchPlaceholder: { en: "Search for parts, brands, or shops...", ar: "ابحث عن قطع، ماركات، أو محلات..." },
  viewDetails: { en: "View Details", ar: "التفاصيل" },
  price: { en: "Price", ar: "السعر" },
  condition: { en: "Condition", ar: "الحالة" },
  new: { en: "New", ar: "جديد" },
  used: { en: "Used", ar: "مستخدم" },
  addToWishlist: { en: "Add to Wishlist", ar: "أضف للمفضلة" },
  contactSeller: { en: "Contact Seller", ar: "تواصل مع البائع" },
  shopName: { en: "Shop", ar: "المتجر" },
  location: { en: "Location", ar: "الموقع" },
  availability: { en: "Availability", ar: "التوفر" },
  inStock: { en: "In Stock", ar: "متوفر" },
  outOfStock: { en: "Out of Stock", ar: "غير متوفر" },
  adminPanel: { en: "Admin Panel", ar: "لوحة الإدارة" },
  sellerZone: { en: "Seller Zone", ar: "منطقة البائعين" },
  myParts: { en: "My Parts", ar: "قطعي" },
  addPart: { en: "Add Part", ar: "إضافة قطعة" },
  sales: { en: "Sales", ar: "المبيعات" },
  users: { en: "Users", ar: "المستخدمين" },
  shops: { en: "Shops", ar: "المحلات" },
  totalRevenue: { en: "Total Revenue", ar: "إجمالي الإيرادات" },
  active: { en: "Active", ar: "نشط" },
  inactive: { en: "Inactive", ar: "غير نشط" },
  suspended: { en: "Suspended", ar: "موقوف" },
  deactivated: { en: "Deactivated", ar: "معطل" },
  compare: { en: "Compare", ar: "مقارنة" },
  contactViaWhatsapp: { en: "Contact via WhatsApp", ar: "تواصل عبر واتساب" },
  callShop: { en: "Call Shop", ar: "اتصل بالمتجر" },
  description: { en: "Description", ar: "الوصف" },
  workingHours: { en: "Working Hours", ar: "ساعات العمل" },
  brands: { en: "Brands", ar: "الماركات" },
  categories: { en: "Categories", ar: "الفئات" },
  inventory: { en: "Inventory", ar: "المخزون" },
  reports: { en: "Reports", ar: "التقارير" },
  costPrice: { en: "Cost Price", ar: "سعر التكلفة" },
  profit: { en: "Profit", ar: "الربح" },
  resetPassword: { en: "Reset Password", ar: "إعادة تعيين كلمة المرور" },
  status: { en: "Status", ar: "الحالة" },
  carBrand: { en: "Car Brand", ar: "ماركة السيارة" },
  category: { en: "Category", ar: "الفئة" },
  websiteSettings: { en: "Website Settings", ar: "إعدادات الموقع" },
  saveChanges: { en: "Save Changes", ar: "حفظ التغييرات" },
  cancel: { en: "Cancel", ar: "إلغاء" },
  edit: { en: "Edit", ar: "تعديل" },
  delete: { en: "Delete", ar: "حذف" },
  whatsapp: { en: "WhatsApp", ar: "واتساب" },
  email: { en: "Email", ar: "البريد الإلكتروني" },
  logoUrl: { en: "Logo URL", ar: "رابط الشعار" },
  
  // Registration
  fullName: { en: "Full Name", ar: "الاسم الكامل" },
  username: { en: "Username", ar: "اسم المستخدم" },
  password: { en: "Password", ar: "كلمة المرور" },
  confirmPassword: { en: "Confirm Password", ar: "تأكيد كلمة المرور" },
  phone: { en: "Phone Number", ar: "رقم الهاتف" },
  city: { en: "City", ar: "المدينة" },
  address: { en: "Address", ar: "العنوان" },
  registerSuccess: { en: "Registration successful!", ar: "تم التسجيل بنجاح!" },
  passwordsDoNotMatch: { en: "Passwords do not match", ar: "كلمات المرور غير متطابقة" },
  usernameTaken: { en: "Username is already taken", ar: "اسم المستخدم مأخوذ مسبقاً" },
  ownedCars: { en: "Car Brands You Own", ar: "ماركات السيارات التي تملكها" },
  preferredCats: { en: "Preferred Categories", ar: "الفئات المفضلة" },
  
  // Admin Add Shop
  addShop: { en: "Add Shop Owner", ar: "إضافة مالك متجر" },
  ownerName: { en: "Shop Owner Name", ar: "اسم مالك المتجر" },
  shopNameField: { en: "Shop Name", ar: "اسم المتجر" },
  latitude: { en: "Latitude", ar: "خط العرض" },
  longitude: { en: "Longitude", ar: "خط الطول" },
  notes: { en: "Notes / Specialization", ar: "ملاحظات / التخصص" },
  headerSettings: { en: "Header Settings", ar: "إعدادات الهيدر" },
  footerSettings: { en: "Footer Settings", ar: "إعدادات الفوتر" },
  socialSettings: { en: "Social Media Settings", ar: "إعدادات التواصل الاجتماعي" },
  contactSettings: { en: "Contact Info Settings", ar: "إعدادات معلومات الاتصال" },
  openMaps: { en: "Open Maps", ar: "افتح الخريطة" },
  
  // Filters
  allUsers: { en: "All Users", ar: "كل المستخدمين" },
  onlySellers: { en: "Sellers", ar: "البائعين" },
  onlyCustomers: { en: "Customers", ar: "العملاء" },
  onlyAdmins: { en: "Admins", ar: "المسؤولين" },
  all: { en: "All", ar: "الكل" },
  
  // Inventory
  stockMovement: { en: "Stock Movement Log", ar: "سجل حركة المخزون" },
  lowStock: { en: "Low Stock Alert", ar: "تنبيه انخفاض المخزون" },
  currentStock: { en: "Current Stock", ar: "المخزون الحالي" },
  changeType: { en: "Change Type", ar: "نوع التغيير" },
  quantity: { en: "Qty", ar: "الكمية" },
  date: { en: "Date", ar: "التاريخ" },
  reason: { en: "Reason", ar: "السبب" },

  // Images
  uploadImage: { en: "Upload Images", ar: "رفع صور" },
  browse: { en: "Browse", ar: "تصفح" },
  maxSize: { en: "Max 2MB per image", ar: "أقصى حجم 2 ميجابايت" },
  remove: { en: "Remove", ar: "إزالة" },
  uploadLogo: { en: "Upload Logo", ar: "رفع الشعار" },

  // Categories
  manageCategories: { en: "Manage Categories", ar: "إدارة الفئات" },
  addCategory: { en: "Add Category", ar: "إضافة فئة" },
  categoryNameEn: { en: "Category Name (EN)", ar: "اسم الفئة (إنجليزي)" },
  categoryNameAr: { en: "Category Name (AR)", ar: "اسم الفئة (عربي)" },
  activeCategories: { en: "Active Categories", ar: "الفئات النشطة" },

  // External Request & Contact
  externalRequest: { en: "External Sales Request", ar: "طلب مبيعات خارجي" },
  requestPart: { en: "Request a Part", ar: "اطلب قطعة" },
  contactUs: { en: "Contact Us", ar: "تواصل بنا" },
  inbox: { en: "Inbox", ar: "صندوق الوارد" },
  sendMessage: { en: "Send Message", ar: "إرسال الرسالة" },
  requestSubmitted: { en: "Your request has been submitted. You will be contacted soon.", ar: "تم تقديم طلبك بنجاح. سيتم التواصل معك قريباً." },
  carModel: { en: "Car Model", ar: "موديل السيارة" },
  modelYear: { en: "Model Year", ar: "سنة الموديل" },
  partDesc: { en: "Part Description", ar: "وصف القطعة" },
  messageBody: { en: "Message", ar: "الرسالة" },
  submit: { en: "Submit", ar: "إرسال" },
  markRead: { en: "Mark as Read", ar: "تمييز كمقروء" },
  reply: { en: "Reply", ar: "رد" },
  from: { en: "From", ar: "من" },
  unreadMessages: { en: "Unread Messages", ar: "رسائل غير مقروءة" },
};
