export const AR = {
  // App
  appName: 'العالمي',
  appTagline: 'سوق قطع غيار السيارات في اليمن والخليج',

  // Location & Header
  myLocation: 'موقعي الحالي',
  defaultCity: 'صنعاء، اليمن',
  notifications: 'الإشعارات',

  // Home Screen (Matches Reference Screen 1)
  heroTitle: 'اعثر على قطع غيار سيارتك',
  heroSubtitle: 'قطع أصلية وتجارية مع ضمان التوافق التام مع سيارتك',
  categories: 'الأقسام الرئيسية',
  viewAll: 'عرض الكل',
  itemsCount: 'قطعة',
  popularProducts: 'المنتجات الأكثر طلباً',
  featuredParts: 'أبرز عروض القطع',
  nearbyShops: 'أقرب المحلات المعتمدة',
  quickGarage: 'كراج سياراتي',

  // Categories Screen (Matches Reference Screen 2)
  browseCategories: 'تصفح الفئات',
  viewAllProducts: 'عرض جميع المنتجات',
  engineOilFluids: 'زيوت وسوائل المحرك',
  filtersMaintenance: 'الفلاتر والصيانة',
  brakeSystem: 'منظومة الفرامل',
  tiresWheels: 'الإطارات والجنوط',
  transmissionOil: 'زيت القير والناقل',
  brakeFluid: 'زيت الفرامل',
  coolant: 'ماء رديتر ومبردات',
  oilFilter: 'فلتر زيت',
  airFilter: 'فلتر هواء ومكيف',
  carCare: 'العناية بالسيارة وملمعات',
  suspension: 'المساعدات والتعليق',
  electrical: 'الكهرباء والبطاريات',

  // Vehicle Selector Screen (Matches Reference Screen 3)
  selectYourVehicle: 'اختر سيارتك',
  selectVehicleSubtitle: 'حدد تفاصيل سيارتك لعرض القطع المتوافقة بنسبة 100%',
  brand: 'الشركة المصنعة',
  selectBrand: 'اختر الشركة (تويوتا، هونداي...)',
  year: 'سنة الصنع',
  selectYear: 'اختر السنة (2024، 2023...)',
  model: 'الموديل',
  selectModel: 'اختر الموديل (كامري، كورولا...)',
  engineType: 'نوع المحرك',
  selectEngine: 'اختر المحرك (2.5L I4، 4.0L V6...)',
  findProduct: 'البحث عن القطع المتوافقة',
  myGarage: 'كراج سياراتي',
  manageAll: 'إدارة الكل',
  addAnotherVehicle: '+ إضافة سيارة أخرى',
  addNewVehicle: '+ إضافة سيارة جديدة',
  compatibleBadge: 'متوافق مع سيارتك المحددة',
  notCompatible: 'غير متوافق',
  thisIsYourVehicle: 'هذه سيارتك',
  saveToGarage: 'حفظ في سياراتي',
  viewCompatibleParts: 'عرض القطع المناسبة',
  setAsActive: 'اختيار كسيارة نشطة',
  activeCarBadge: 'السيارة النشطة',
  deleteVehicle: 'حذف',
  confirmDeleteVehicle: 'هل تريد إزالة هذه السيارة من كراجك؟',
  noVehiclesSaved: 'لا توجد سيارات محفوظة',
  noVehiclesSavedSub: 'أضف سيارتك للوصول بسرعة إلى القطع المتوافقة معها.',
  confirmVehicle: 'تأكيد السيارة',
  cancel: 'إلغاء',
  searchThisVehicle: 'بحث عن قطع متوافقة',
  subcategories: 'الأقسام الفرعية',
  partTypes: 'أنواع القطع',
  filterByTaxonomy: 'تصفح شجرة القطع المرجعية',

  // Product Card & Details
  partNo: 'رقم القطعة',
  oemNo: 'رقم OEM',
  compatibleWith: 'متوافق مع',
  shop: 'المحل',
  inStock: 'متوفر',
  outOfStock: 'نفذت الكمية',
  contactShop: 'تواصل مع المحل',
  addToCart: 'إضافة إلى السلة',
  buyNow: 'شراء فوري',
  otherOffers: 'عروض أخرى لنفس القطعة',
  specifications: 'المواصفات الفنية',
  description: 'الوصف',
  reviews: 'التقييمات',
  condition: 'الحالة',
  conditionNew: 'جديد',
  conditionUsed: 'مستعمل',
  conditionOem: 'أصلي OEM',
  conditionAftermarket: 'تجاري معتمد',

  // Search
  searchPlaceholder: 'ابحث باسم القطعة، رقم OEM، أو رقم القطعة...',
  recentSearches: 'عمليات البحث الأخيرة',
  filters: 'الفلاتر',
  priceRange: 'نطاق السعر',
  allMakes: 'كل السيارات',
  sortBy: 'الترتيب حسب',
  sortBestMatch: 'الأكثر صلة',
  sortPriceAsc: 'السعر: من الأقل',
  sortPriceDesc: 'السعر: من الأعلى',
  sortRating: 'الأعلى تقييماً',

  // Cart & Checkout
  cart: 'السلة',
  cartEmpty: 'السلة فارغة',
  cartEmptySub: 'تصفح القطع المتوافقة وأضف ما تحتاجه لسلتك',
  subtotal: 'المجموع الفرعي',
  deliveryFee: 'رسوم التوصيل',
  total: 'الإجمالي النهائي',
  proceedCheckout: 'متابعة الدفع (Checkout)',
  deliveryAddress: 'عنوان التوصيل',
  deliveryMethod: 'طريقة التوصيل',
  pickupFromShop: 'استلام من المحل',
  shopDelivery: 'توصيل عبر المحل',
  deliveryCompany: 'شركة توصيل سريعة',
  paymentMethod: 'طريقة الدفع',
  cashOnDelivery: 'الدفع عند الاستلام',
  bankTransfer: 'تحويل بنكي',
  walletPayment: 'محفظة إلكترونية',
  orderSuccess: 'تم إنشاء الطلب بنجاح!',

  // Orders
  myOrders: 'طلباتي',
  orderId: 'رقم الطلب',
  orderDate: 'تاريخ الطلب',
  statusPending: 'طلب جديد',
  statusConfirmed: 'تم التأكيد',
  statusPreparing: 'قيد التجهيز',
  statusReady: 'جاهز للاستلام/الشحن',
  statusDelivered: 'تم التسليم',
  statusCancelled: 'ملغي',

  // Shop Panel
  shopDashboard: 'لوحة إدارة المحل',
  monthSales: 'مبيعات الشهر',
  activeOrders: 'الطلبات النشطة',
  totalProducts: 'إجمالي القطع',
  lowStockCount: 'تنبيهات نقص المخزون',
  manageProducts: 'إدارة المنتجات والأسعار',
  adjustStock: 'جرد وتعديل المخزون',
  teamPermissions: 'فريق العمل والصلاحيات',
  branchManagement: 'إدارة الفروع',
  priceVisibility: 'ظهور السعر للعملاء',
  showPrice: 'عرض السعر',
  hidePrice: 'إخفاء السعر (تواصل معنا)',

  // Admin Panel
  adminConsole: 'لوحة الإدارة العامة',
  approvedShops: 'المحلات المعتمدة',
  pendingShops: 'طلبات محلات جديدة',
  totalGmv: 'إجمالي المبيعات',
  commissions: 'عمولات المنصة',
  approveShop: 'موافقة وتعيين العمولة',
  rejectShop: 'رفض المحل',
  vehicleDatabase: 'شجرة السيارات ومحركاتها',

  // Profile & Auth
  profile: 'الملف الشخصي',
  personalInfo: 'المعلومات الشخصية',
  savedVehicles: 'السيارات المحفوظة',
  language: 'اللغة / Language',
  arabic: 'عربي',
  english: 'English',
  demoSwitcherTitle: 'تبديل الحساب التجريبي',
  demoSwitcherSub: 'اختر حساباً لاختبار الواجهات والصلاحيات لكل دور',
  logout: 'تسجيل الخروج',
  signIn: 'تسجيل الدخول',
  createAccount: 'إنشاء حساب جديد',
  phoneOtp: 'الدخول عبر رقم الهاتف وOTP',
  anyOtpWorks: 'أي رمز مكون من 6 أرقام يعمل (مثل 123456)',
};
