export const EN = {
  // App
  appName: 'ALALAMI',
  appTagline: 'Auto Spare Parts Marketplace in Yemen & GCC',

  // Location & Header
  myLocation: 'My Location',
  defaultCity: "Sana'a, Yemen",
  notifications: 'Notifications',

  // Home Screen (Matches Reference Screen 1)
  heroTitle: 'Find Your Car Equipment',
  heroSubtitle: 'Genuine & certified spare parts with 100% guaranteed vehicle fitment',
  categories: 'Categories',
  viewAll: 'View All',
  itemsCount: 'items',
  popularProducts: 'Popular Products',
  featuredParts: 'Featured Part Deals',
  nearbyShops: 'Nearby Verified Shops',
  quickGarage: 'My Garage',

  // Categories Screen (Matches Reference Screen 2)
  browseCategories: 'Browse Categories',
  viewAllProducts: 'View All Products',
  engineOilFluids: 'Engine Oil & Fluids',
  filtersMaintenance: 'Filters & Maintenance',
  brakeSystem: 'Brake System',
  tiresWheels: 'Tires & Wheels',
  transmissionOil: 'Transmission Oil',
  brakeFluid: 'Brake Fluid',
  coolant: 'Coolant & Fluids',
  oilFilter: 'Oil Filter',
  airFilter: 'Air Filter',
  carCare: 'Car Care & Detailing',
  suspension: 'Suspension & Shocks',
  electrical: 'Electrical & Batteries',

  // Vehicle Selector Screen (Matches Reference Screen 3)
  selectYourVehicle: 'Select Your Vehicle',
  selectVehicleSubtitle: 'Tell us what you drive to find parts that fit perfectly',
  brand: 'Brand',
  selectBrand: 'Select Brand (Toyota, Hyundai...)',
  year: 'Year',
  selectYear: 'Select year (2024, 2023...)',
  model: 'Model',
  selectModel: 'Select model (Camry, Corolla...)',
  engineType: 'Engine Type',
  selectEngine: 'Select Engine (2.5L I4, 4.0L V6...)',
  findProduct: 'Find Product',
  myGarage: 'My Garage',
  manageAll: 'Manage All',
  addAnotherVehicle: '+ Add Another Vehicle',
  addNewVehicle: '+ Add New Vehicle',
  compatibleBadge: 'Fits your selected vehicle',
  notCompatible: 'Does not fit',
  thisIsYourVehicle: 'This is your vehicle',
  saveToGarage: 'Save to My Garage',
  viewCompatibleParts: 'View Compatible Parts',
  setAsActive: 'Set as Active',
  activeCarBadge: 'Active Vehicle',
  deleteVehicle: 'Delete',
  confirmDeleteVehicle: 'Are you sure you want to remove this vehicle from your garage?',
  noVehiclesSaved: 'No saved vehicles',
  noVehiclesSavedSub: 'Add your vehicle to quickly find parts guaranteed to fit.',
  confirmVehicle: 'Confirm Vehicle',
  cancel: 'Cancel',
  searchThisVehicle: 'Search parts for this vehicle',
  subcategories: 'Subcategories',
  partTypes: 'Part Types',
  filterByTaxonomy: 'Browse Parts Directory',

  // Product Card & Details
  partNo: 'Part #',
  oemNo: 'OEM #',
  compatibleWith: 'Compatible With',
  shop: 'Shop',
  inStock: 'In Stock',
  outOfStock: 'Out of Stock',
  contactShop: 'Contact Shop',
  addToCart: 'Add to Cart',
  buyNow: 'Buy Now',
  otherOffers: 'Other Shop Offers for this Part',
  specifications: 'Specifications',
  description: 'Description',
  reviews: 'Reviews',
  condition: 'Condition',
  conditionNew: 'New',
  conditionUsed: 'Used',
  conditionOem: 'OEM Genuine',
  conditionAftermarket: 'Certified Aftermarket',

  // Search
  searchPlaceholder: 'Search part name, OEM, or part #...',
  recentSearches: 'Recent Searches',
  filters: 'Filters',
  priceRange: 'Price Range',
  allMakes: 'All Makes',
  sortBy: 'Sort By',
  sortBestMatch: 'Best Match',
  sortPriceAsc: 'Price: Low to High',
  sortPriceDesc: 'Price: High to Low',
  sortRating: 'Top Rated',

  // Cart & Checkout
  cart: 'Cart',
  cartEmpty: 'Your cart is empty',
  cartEmptySub: 'Browse compatible parts and add what you need',
  subtotal: 'Subtotal',
  deliveryFee: 'Delivery Fee',
  total: 'Total Amount',
  proceedCheckout: 'Proceed to Checkout',
  deliveryAddress: 'Delivery Address',
  deliveryMethod: 'Delivery Method',
  pickupFromShop: 'Pickup from Shop',
  shopDelivery: 'Direct Shop Delivery',
  deliveryCompany: 'Express Courier',
  paymentMethod: 'Payment Method',
  cashOnDelivery: 'Cash on Delivery',
  bankTransfer: 'Bank Transfer',
  walletPayment: 'E-Wallet',
  orderSuccess: 'Order placed successfully!',

  // Orders
  myOrders: 'My Orders',
  orderId: 'Order #',
  orderDate: 'Date',
  statusPending: 'New Order',
  statusConfirmed: 'Confirmed',
  statusPreparing: 'Preparing',
  statusReady: 'Ready for Pickup',
  statusDelivered: 'Delivered',
  statusCancelled: 'Cancelled',

  // Shop Panel
  shopDashboard: 'Shop Dashboard',
  monthSales: 'Month Sales',
  activeOrders: 'Active Orders',
  totalProducts: 'Total Parts',
  lowStockCount: 'Low Stock Alerts',
  manageProducts: 'Manage Products & Prices',
  adjustStock: 'Stock Adjustment & Branches',
  teamPermissions: 'Team & Custom Permissions',
  branchManagement: 'Branches',
  priceVisibility: 'Price Visibility',
  showPrice: 'Show Price',
  hidePrice: 'Hide Price (Contact Shop)',

  // Admin Panel
  adminConsole: 'Admin Console',
  approvedShops: 'Approved Shops',
  pendingShops: 'Pending Shop Approvals',
  totalGmv: 'Total GMV Sales',
  commissions: 'Platform Commissions',
  approveShop: 'Approve & Set Commission',
  rejectShop: 'Reject Shop',
  vehicleDatabase: 'Vehicle Fitment Database',

  // Profile & Auth
  profile: 'Profile',
  personalInfo: 'Personal Information',
  savedVehicles: 'My Vehicles',
  language: 'Language / اللغة',
  arabic: 'عربي',
  english: 'English',
  demoSwitcherTitle: 'Switch Demo Account',
  demoSwitcherSub: 'Select an account to test role permissions',
  logout: 'Log Out',
  signIn: 'Sign In',
  createAccount: 'Create Account',
  phoneOtp: 'Login with Phone & OTP',
  anyOtpWorks: 'Any 6-digit code works (e.g. 123456)',
};
